### ISSUE TITLE
Possible bug using chmod

### ISSUE THREAD

**Issue by moviuro** [GInfo-ECM/club-drupal#1]
In `bin/all-reset-permissions.sh` and `bin/d7-create-site.sh`, we use `chmod <numbers>`, which is dangerous:
What happens with: `chmod -R 700 foo/` ? `foo/bar` become executable, which is perhaps not intended.

Better use `chmod -R go-rwx foo/`

**Comment by Jenselme** [comment]
I  think `chmod u=rwx,go-rwx <folder>` is the appropriate command:
- only assos can go trough the folder
- we are certain that assos can (avoid the problem of non executable site folder).

**Comment by moviuro** [comment]
`chmod u=rwx,go= <folder>` would be better IMO

**Comment by Jenselme** [comment]
Indeed. Thanks.

**Comment by Jenselme** [comment]
I guess we could also use [OSSEC](http://www.ossec.net/) or [monit](https://mmonit.com/monit/) but I think this is overkill in this case.

**Comment by FlorentTorregrosa** [comment]
Hello,
Thanks for this thinking.

So your choice is `chmod u=rwx,go= foo/` but is this not equivalent to `chmod 700 foo/` ? So the problem is just to remove the `-R` option ?

But if we remove the -R option, if by example there are some backup files with 777 permissions for any reason. There is no command that will change the permissions to 700 ?

**Comment by Jenselme** [comment]
> But if we remove the -R option, if by example there are some backup files with 777 permissions for any reason. There is no command that will change the permissions to 700 ?

Only assos can go through them since the folder containing them has 700 perm.

**Comment by moviuro** [comment]
> if by example there are some backup files with 777 permissions for any reason.

@FlorentTorregrosa then your backup script is broken. You should either use:
`find /foo -type f -exec chmod -x {} \;`
`find /foo -type d -exec chmod 755 {} \;`
The main idea is: don't use the `-R` switch if it causes to apply the same `chmod` to files and folders.

**Comment by FlorentTorregrosa** [comment]
Ok, so `chmod -R 700 foo/` needs to become `chmod 700 foo/`.

**Comment by Jenselme** [comment]
I think so.

**Comment by dgeo** [comment]
1. correct rights for non-executable files (alamain)
2. `chmod -R u+rXw,go-rxw dirname`

**Comment by Jenselme** [comment]
I did `for file in $(find . -type f); do chmod 600 "$file"; done` to fix the permissions in:
- `"${dir_backup}"`
- `"${dir_log}"`
- `"${dir_private}"`

And fix the scripts based on @dgeo's answer with 35e0bbf438.

For explanations on `chmod -R u+rXw` see: http://www.jujens.eu/posts/2014/Sep/07/diverses-astuces-shell/#chmod-a-x (in French).
